services:

  blaubot:
    image: bluefireoly/blaubot:latest
    volumes:
      - ./config:/app/config/

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 120
